version: '3'
services:
  master:
    build:
      context: pythonProject/master
    network_mode: "host"
    container_name: master

  slave1:
    build:
      context: slave_1
    network_mode: "host"
    container_name: slave_1

  slave2:
    build:
      context: slave_2
    network_mode: "host"
    container_name: slave_2
