version: '3'
services:
  master:
    build:
      context: master
    network_mode: "host"
    environment:
      - HOST=0.0.0.0
      - PORT=5003
    container_name: master

  slave1:
    build:
      context: slave
    network_mode: "host"
    environment:
      - HOST=0.0.0.0
      - PORT=5001
      - TIME_SLEEP_IN_SEC=10
    container_name: slave_1

  slave2:
    build:
      context: slave
    network_mode: "host"
    environment:
      - HOST=0.0.0.0
      - PORT=5002
      - TIME_SLEEP_IN_SEC=30
    container_name: slave_2
